# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fibo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfibo.proto\"\x1d\n\x0b\x43\x61lcRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"1\n\x0c\x43\x61lcResponse\x12\x11\n\tprocessId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1f\n\nGetRequest\x12\x11\n\tprocessId\x18\x01 \x01(\t\"-\n\x0bGetResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\t2d\n\tFibonacci\x12,\n\rCalcFibonacci\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12)\n\x0cGetFibonacci\x12\x0b.GetRequest\x1a\x0c.GetResponseB<Z:github.com/sergiovenicio/grpc-server-example/infra/grpc/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fibo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/sergiovenicio/grpc-server-example/infra/grpc/pb'
  _CALCREQUEST._serialized_start=14
  _CALCREQUEST._serialized_end=43
  _CALCRESPONSE._serialized_start=45
  _CALCRESPONSE._serialized_end=94
  _GETREQUEST._serialized_start=96
  _GETREQUEST._serialized_end=127
  _GETRESPONSE._serialized_start=129
  _GETRESPONSE._serialized_end=174
  _FIBONACCI._serialized_start=176
  _FIBONACCI._serialized_end=276
# @@protoc_insertion_point(module_scope)
